version: 2

registries:
  nuget-github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/xt0rted/index.json
    token: ${{ secrets.GPR_READ_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "actions/*"
      my-actions:
        patterns:
          - "xt0rted/*"

  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
    groups:
      analyzers:
        patterns:
          - "IDisposableAnalyzers"
          - "Roslynator.*"
      system-io:
        patterns:
          - "System.IO.Abstractions"
          - "System.IO.Abstractions.TestingHelpers"
      testing:
        patterns:
          - "coverlet.collector"
          - "FakeItEasy"
          - "FakeItEasy.*"
          - "Microsoft.NET.Test.Sdk"
          - "Shouldly"
          - "Verify.Xunit"
          - "xunit"
          - "xunit.*"
