name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true
  CONFIGURATION: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - macos-13
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022

    permissions:
      contents: read
      packages: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.2

      - name: Build version suffix (main)
        if: github.event_name == 'push'
        run: echo "VERSION_SUFFIX=beta.${{ github.run_number }}" >> $GITHUB_ENV
        shell: bash

      - name: Build version suffix (pr)
        if: github.event_name == 'pull_request'
        run: echo "VERSION_SUFFIX=alpha.${{ github.event.number }}" >> $GITHUB_ENV
        shell: bash

      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          source-url: https://nuget.pkg.github.com/xt0rted/index.json
          nuget_auth_token: ${{ secrets.GITHUB_TOKEN }}
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x

      - run: dotnet tool restore

      - run: dotnet r build

      - run: dotnet r test -- --no-build --logger GitHubActions

      - run: dotnet r pack -- --no-build --version-suffix ${{ env.VERSION_SUFFIX }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.1
        if: matrix.os == 'ubuntu-22.04'
        with:
          name: nupkg
          path: ./artifacts/*.nupkg

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: build-verify-test-results
          path: |
            **/*.received.*

  release:
    if: github.event_name == 'push'

    needs: build

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Download nupkg
        uses: actions/download-artifact@v4.1.4
        with:
          name: nupkg

      - name: Publish to GPR
        run: |
          dotnet nuget push "./*.nupkg" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}
