name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true
  CONFIGURATION: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022

    permissions:
      contents: read
      packages: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.1.0

      - name: Build version suffix (main)
        if: github.event_name == 'push'
        run: echo "VERSION_SUFFIX=beta.${{ github.run_number }}" >> $GITHUB_ENV
        shell: bash

      - name: Build version suffix (pr)
        if: github.event_name == 'pull_request'
        run: echo "VERSION_SUFFIX=alpha.${{ github.event.number }}" >> $GITHUB_ENV
        shell: bash

      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.4.0
        with:
          source-url: https://nuget.pkg.github.com/xt0rted/index.json
          nuget_auth_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.4.0
        if: matrix.os == 'ubuntu-22.04'
        with:
          colored-output: false
          strip-comments-from-global-json: false
          dotnet-version: |
            3.1.x
            5.0.x

      - run: dotnet tool restore

      - run: dotnet r build

      - run: dotnet r test -- --logger "trx;LogFilePrefix=${{ matrix.os }}"

      - run: dotnet r pack -- --version-suffix ${{ env.VERSION_SUFFIX }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.1
        if: matrix.os == 'ubuntu-20.04'
        with:
          name: nupkg
          path: ./artifacts/*.nupkg

      - name: Upload test results
        uses: actions/upload-artifact@v3.1.1
        if: always()
        with:
          name: test-results
          path: ./.coverage/*.trx

  release:
    if: github.event_name == 'push'

    needs: build

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Download nupkg
        uses: actions/download-artifact@v3.0.0
        with:
          name: nupkg

      - name: Publish to GPR
        run: |
          dotnet nuget push "./*.nupkg" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}
